const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'lang', 'en.json');
let raw = fs.readFileSync(file, 'utf8');
if (raw.charCodeAt(0) === 0xFEFF) raw = raw.slice(1);
const data = JSON.parse(raw);

const entries = {
  setcmd: 'Save a custom command and its reply',
  getcmd: 'List or view a custom command',
  delcmd: 'Delete a custom command',
  listcmd: 'List all custom commands',
  setgreet: 'Set custom welcome/goodbye message template',
  getgreet: 'View saved welcome/goodbye templates',
  delgreet: 'Delete a welcome or goodbye template',
  mode: 'View or change bot mode (public/private/inbox/groups)',
  vv: 'Reveal view-once media as a normal message',
  uptime: 'Show how long the bot has been running',
  owner: 'Get the bot owner contact details',
  repo: 'Get the Titan MD repository link',
  language: 'View or change the bot language',
  cancel: 'Cancel a pending scheduled message',
  retry: 'Retry the last failed command',
  edit: 'Edit the bot last sent message',
  dyno: 'Restart Heroku/Render dyno',
  dall: 'Delete all bot messages in the chat',
  read: 'Mark current chat as read',
  fullss: 'Take a full-page screenshot of a URL',
  setsudo: 'Add a user to the sudo list',
  getsudo: 'Show all sudo users',
  delsudo: 'Remove a user from the sudo list',
  resetwarn: 'Reset all warns for a user or group',
  rmwarn: 'Remove one warn from a user',
  setwarnlimit: 'Set the maximum warns before kick',
  warnlist: 'List all warned users in the current group',
  warnstats: 'Show total warning statistics',
  antibot: 'Toggle auto-kick for bots in the group',
  antipromote: 'Auto-revert promotion changes made by non-bot',
  antidemote: 'Auto-revert demotion changes made by non-bot',
  slow: 'Toggle slow mode for the group',
  slowmo: 'Alias for slow mode toggle',
  stickcmd: 'Bind a sticker to a command (sticker triggers command)',
  unstick: 'Unbind a sticker command',
  getstick: 'List all sticker-bound commands',
  fullgpp: 'Show the full-size group profile picture',
  setmention: 'Toggle whether bot replies to mentions',
  setgpp: 'Set group profile picture from replied image',
  admins: 'List all admins in the current group',
  listadmin: 'List all admins in the current group',
  metallic: 'Generate metallic text-effect sticker',
  ice: 'Generate ice text-effect sticker',
  neon: 'Generate neon text-effect sticker',
  snow: 'Generate snow text-effect sticker',
  matrix: 'Generate matrix text-effect sticker',
  devil: 'Generate devil text-effect sticker',
  thunder: 'Generate thunder text-effect sticker',
  leaves: 'Generate leaves text-effect sticker',
  '1917': 'Generate 1917-style text-effect sticker',
  arena: 'Generate arena text-effect sticker',
  hacker: 'Generate hacker text-effect sticker',
  sand: 'Generate sand text-effect sticker',
  blackpink: 'Generate Blackpink text-effect sticker',
  glitch: 'Generate glitch text-effect sticker',
  fire: 'Generate fire text-effect sticker',
  light: 'Generate light text-effect sticker',
  purple: 'Generate purple text-effect sticker',
  impressive: 'Generate impressive text-effect sticker',
  hug: 'Send an anime hug reaction',
  pat: 'Send an anime pat reaction',
  poke: 'Send an anime poke reaction',
  cry: 'Send an anime cry reaction',
  wink: 'Send an anime wink reaction',
  nom: 'Send an anime nom reaction',
  pies: 'Country-themed pies sticker',
  china: 'China-themed sticker',
  japan: 'Japan-themed sticker',
  korea: 'Korea-themed sticker',
  india: 'India-themed sticker',
  indonesia: 'Indonesia-themed sticker',
  malaysia: 'Malaysia-themed sticker',
  thailand: 'Thailand-themed sticker',
  translate: 'Translate text to another language',
  upscale: 'Upscale image quality 4x using AI',
  tg: 'Download a Telegram sticker pack',
  tgsticker: 'Download a Telegram sticker pack',
  telesticker: 'Download a Telegram sticker pack',
  stickertelegram: 'Download a Telegram sticker pack',
  bank: 'Show your bank balance',
  deposit: 'Deposit coins from wallet to bank',
  withdraw: 'Withdraw coins from bank to wallet',
  transfer: 'Transfer coins to another user',
  give: 'Give coins to another user (alias of transfer)',
  gamble: 'Gamble coins (50/50 chance)',
  slot2: 'Premium slot machine with jackpot',
  lb: 'Show economy leaderboard (top 10)',
  wallet: 'Show your wallet balance (alias of money)',
  voice: 'Convert replied audio to voice note',
  toaudio: 'Convert video to audio file',
  tomp3: 'Convert media to MP3 audio',
  tovideo: 'Convert media to MP4 video',
  tomp4: 'Convert media to MP4 video',
  sound: 'Extract sound from a video',
  fliptext: 'Flip text upside down',
  ttp: 'Generate text-to-picture sticker',
  tourl: 'Upload a file and get a public URL',
  paste: 'Upload text to pastebin and get URL',
  pick: 'Randomly pick one option from a list',
  tiny: 'Shorten a long URL',
  num: 'Look up info about a phone number',
  dbinary: 'Decode a binary string to text',
  ebinary: 'Encode text to a binary string',
};

if (!data.plugins) data.plugins = {};

let added = 0, skipped = 0;
for (const [name, desc] of Object.entries(entries)) {
  if (data.plugins[name]) { skipped++; continue; }
  data.plugins[name] = { desc };
  added++;
}

fs.writeFileSync(file, JSON.stringify(data, null, 4), 'utf8');
console.log('added:', added, 'skipped:', skipped, 'total plugin keys:', Object.keys(data.plugins).length);
console.log('box ok:', data.plugins.menu && data.plugins.menu.header ? data.plugins.menu.header.includes('╭') : 'no menu.header');
